# Generated by Django 5.1.7 on 2025-03-08 17:16

from django.db import migrations


def add_agent_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="agent")


class Migration(migrations.Migration):

    dependencies = [
        ("customer_messages", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_agent_group),
    ]
